### PR TITLE
Refactor code

### PR DESCRIPTION
**Pull request by zaynetro**
Convert tabs to spaces, apply the same style for the whole code, fix some indentation.

### CODE REVIEW

**Comment by timojaask** [comment]
Why did you decide to discard my pull request entirely and start from scratch?

**Comment by daitj** [comment]
@zaynetro i think we should first merge the dev branch to master

**Comment by zaynetro** [comment]
@themightydeity sure, I haven't noticed that branch and refactored the master just to get the idea what's on the server side

**Comment by timojaask** [comment]
So what do we do? Do we discard what I did or?

**Comment by daitj** [comment]
Discard refactoring. Merge the pull request that is pending in dev branch.

**Comment by zaynetro** [comment]
@themightydeity then, please, do

**Comment by daitj** [comment]
i will close this, @zaynetro you can refactor code if you want to and then you can make a pull request

**Pull request closed without merging**
