### PR TITLE
No output on invalid request

### PR DESCRIPTION
**Pull request by sarukuku**
Silence is golden. Write no output if the request is invalid. It adds no value and writing nothing to the output might give a slight added (but false) feeling of security. If someone stumbles on the page and sees nothing he's probably less likely to start investigating where he's at.

Use exit; insted of die(); as it has less characters and it's [theoretically faster](http://stackoverflow.com/questions/1795025/what-are-the-differences-in-die-and-exit-in-php#answer-13180118).

### CODE REVIEW

**Comment by timojaask** [comment]
We could also check for invalid or missing parameters in other methods, and if there is any error, not print anything. In this way, only the properly constructed calls would give a response.

By the way, we should clean up the entire api and get rid of all the mess :D But that's another issue perhaps.

**Comment by daitj** [comment]
+1 for this, if anyone fixes the validation please do remember to remove
TODO: comment I have added in the code.

**Comment by sarukuku** [comment]
@timojaask One step at a time :) This is probably safe to merge?

**Comment by timojaask** [comment]
@sarukuku :+1:

**Pull request merged**
