### PR TITLE
I guess this one is better right?

### PR DESCRIPTION
**Pull request by daitj**
Fixed the issue that was raised by Timo, also now I am confused about the else if on Line 93. I added this since there will be also such conditions in our requests right?

### CODE REVIEW

**Comment by zaynetro** [comment]
Still no progress with this?

**Comment by daitj** [comment]
waiting for you guys to review it, if it is okay or we need to update it?

**Comment by zaynetro** [comment]
@timojaask

**Comment by timojaask** [comment]
Sorry guys, I've just been real busy these days trying to wrap up the projects
in my old workplace and get up to speed with my new work. I will set some
time to look into this during this weekend. Cheers!

On Thu, Aug 21, 2014 at 6:28 PM, Roman Zaynetdinov <notifications@github.com

**Comment by zaynetro** [comment]
Server side updated as well

**Pull request merged**
